[[main]]
  name = "Events"
  pageRef = "categories/events"
  weight = 10

[[main]]
  name = "Vegas"
  pageRef = "categories/vegas"
  weight = 20

[[main]]
  name = "Vegas Insider"
  pageRef = "categories/vegas-insider"
  weight = 30

[[main]]
  name = "Vegas Life"
  pageRef = "categories/vegas-life"
  weight = 40

[[main]]
  name = "Search"
  pageRef = "search"
  weight = 50
